	<!--
		@Item: Menu
		@Autor: Pedro Realinho
		@Contributor: Filipe Revez
	-->


	<nav>
		<i title="Brainstorm" data-toggle="tooltip" data-placement="bottom" class="round blue fa fa-cloud"></i>
		<i class="fa fa-angle-right"></i>
		<i title="cenas" data-toggle="tooltip" data-placement="bottom"  class="round fa fa-pencil-square-o"></i>
		<i class="fa fa-angle-right"></i>
		<i title="Plan" data-toggle="tooltip" data-placement="bottom" class="round green fa fa-list-alt"></i>
		<i class="fa fa-angle-right"></i>
		<i title="Code" data-toggle="tooltip" data-placement="bottom" class="round fa fa-code"></i>
		<i class="fa fa-angle-right"></i>
		<i title="Execute" data-toggle="tooltip" data-placement="bottom" class="round orange fa fa-file-code-o"></i>
		<i class="fa fa-angle-right"></i>
		<i title="Share" data-toggle="tooltip" data-placement="bottom" class="round fa fa-code-fork"></i>
		<i class="fa fa-angle-right"></i>
		<i title="Deploy" data-toggle="tooltip" data-placement="bottom" class="round yellow fa fa-paper-plane"></i>
		<i class="fa fa-angle-right"></i>
		<i title="Control" data-toggle="tooltip" data-placement="bottom" class="round black fa fa-bug"></i>
		<!-- <ul>
			<li></li>
		</ul> -->
	</nav>